services:
  postgres:
    image: postgres:16-alpine
    container_name: deepfine-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deepfine
      POSTGRES_USER: deepfine
      POSTGRES_PASSWORD: deepfine
    volumes:
      - deepfine-postgres-data:/var/lib/postgresql/data

volumes:
  deepfine-postgres-data:
